/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pidev.presentation;

import java.util.Date;
import javax.swing.*;
import pidev.dao.AnnonceDAO;
import pidev.entities.Annonce;
import pidev.util.MyConnection;



/**
 *
 * @author chiheb
 */
public class AjouterAnnonce_Responsable extends javax.swing.JFrame {

    /**
     * Creates new form AjouterAnnonce_Responsable
     */
    public AjouterAnnonce_Responsable() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAdesc = new javax.swing.JTextArea();
        TFdepart = new javax.swing.JTextField();
        CboxTypeHeberg = new javax.swing.JComboBox();
        CboxTheme = new javax.swing.JComboBox();
        TFdestination = new javax.swing.JTextField();
        TFnom = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        BtnAjouterAnnonce = new javax.swing.JButton();
        CboxTransport = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CboxNote = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TfHebergement = new javax.swing.JTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Avion", "Camping-Car", "Bus", "Micro-Bus ", "Mini-Bus", "Voiture", " ", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(44, 62, 80));
        jLabel2.setText("Date Depart ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 280, 110, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(44, 62, 80));
        jLabel4.setText("Nom ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 190, 60, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(44, 62, 80));
        jLabel5.setText("Date Retour ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 310, 100, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(44, 62, 80));
        jLabel6.setText("Depart ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 350, 70, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(44, 62, 80));
        jLabel7.setText("Type Hebergement ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 510, 150, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(44, 62, 80));
        jLabel8.setText("Destination ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 400, 100, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(44, 62, 80));
        jLabel9.setText("Description");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 450, 100, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(44, 62, 80));
        jLabel10.setText("Transport ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(80, 550, 100, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(44, 62, 80));
        jLabel11.setText("Thème");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(80, 240, 120, 17);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        TAdesc.setColumns(20);
        TAdesc.setRows(5);
        jScrollPane1.setViewportView(TAdesc);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(240, 430, 190, 60);

        TFdepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFdepartActionPerformed(evt);
            }
        });
        getContentPane().add(TFdepart);
        TFdepart.setBounds(240, 350, 190, 30);

        CboxTypeHeberg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Auberge", "Bungalow", "Hotel 1 etoile ", "Hotel 2 etoiles ", "Hotel 3 etoiles ", "Hotel 4 etoiles", "Hotel 5 etoiles", "Residence  ", "Villa", " " }));
        CboxTypeHeberg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboxTypeHebergActionPerformed(evt);
            }
        });
        getContentPane().add(CboxTypeHeberg);
        CboxTypeHeberg.setBounds(240, 510, 190, 30);

        CboxTheme.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Affaire", "Bien etre", "Camping", "Excursion", "Randonnée", "Voyage de découverte ", "Voyage de noce ", " " }));
        CboxTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboxThemeActionPerformed(evt);
            }
        });
        getContentPane().add(CboxTheme);
        CboxTheme.setBounds(240, 230, 190, 30);

        TFdestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFdestinationActionPerformed(evt);
            }
        });
        getContentPane().add(TFdestination);
        TFdestination.setBounds(240, 390, 190, 30);

        TFnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnomActionPerformed(evt);
            }
        });
        getContentPane().add(TFnom);
        TFnom.setBounds(240, 190, 190, 30);

        jButton1.setText("Annuler");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 650, 90, 23);

        BtnAjouterAnnonce.setText("Ajouter ");
        BtnAjouterAnnonce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAjouterAnnonceActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAjouterAnnonce);
        BtnAjouterAnnonce.setBounds(360, 650, 90, 23);

        CboxTransport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "AVION", "BUS ", "MACRO-BUS", "MINI-BUS", "VOITURE" }));
        getContentPane().add(CboxTransport);
        CboxTransport.setBounds(240, 550, 190, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Ajouter Annonce ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 120, 230, 29);

        jLabel3.setText("le nom du responsable");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(520, 120, 130, 14);

        jLabel12.setText("le nom de l'agence");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 120, 130, 14);

        CboxNote.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", " 1", " 2", " 3", " 4", " 5", " 6", " 7", " 8", " 9", " 10", " 11", " 12", " 13", " 14", " 15", " 16", " 17", " 18", " 19", " 20" }));
        getContentPane().add(CboxNote);
        CboxNote.setBounds(240, 600, 190, 22);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(44, 62, 80));
        jLabel13.setText("Note");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(90, 600, 50, 17);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(44, 62, 80));
        jLabel14.setText("Hebergement");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(450, 510, 110, 20);
        getContentPane().add(TfHebergement);
        TfHebergement.setBounds(560, 510, 140, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFdepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFdepartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFdepartActionPerformed

    private void CboxThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxThemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboxThemeActionPerformed

    private void TFdestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFdestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFdestinationActionPerformed

    private void TFnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnomActionPerformed

    private void BtnAjouterAnnonceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAjouterAnnonceActionPerformed
        JOptionPane d = new JOptionPane();

        Annonce a = new Annonce();
        AnnonceDAO aDAO = new AnnonceDAO();
        a.setNom(TFnom.getText());
        a.setType_annonce(CboxTheme.getSelectedItem().toString());


//        a.setDate_deb(JXDateDepart.getDate());
//        a.setDate_fin(JXDateRetour.getDate());
        a.setDepart(TFdepart.getText());
        a.setDestination(TFdestination.getText());
        a.setType_annonce(CboxTypeHeberg.getSelectedItem().toString());
        a.setTransport(CboxTransport.getSelectedItem().toString());
        aDAO.InsertAnnonce(a);
    }//GEN-LAST:event_BtnAjouterAnnonceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void CboxTypeHebergActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxTypeHebergActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboxTypeHebergActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        ResponsableAgence RA = new ResponsableAgence();
        this.dispose();
        RA.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterAnnonce_Responsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterAnnonce_Responsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterAnnonce_Responsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterAnnonce_Responsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjouterAnnonce_Responsable().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAjouterAnnonce;
    private javax.swing.JComboBox CboxNote;
    private javax.swing.JComboBox CboxTheme;
    private javax.swing.JComboBox CboxTransport;
    private javax.swing.JComboBox CboxTypeHeberg;
    private javax.swing.JTextArea TAdesc;
    private javax.swing.JTextField TFdepart;
    private javax.swing.JTextField TFdestination;
    private javax.swing.JTextField TFnom;
    private javax.swing.JTextField TfHebergement;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
