/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pidev.presentation;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import pidev.util.MyConnection;

/**
 *
 * @author Abdelaziz
 */
public class Chiheb_Authentification extends javax.swing.JFrame {

    /**
     * Creates new form Acceuil
     */
    int variable2;
    int  x=0 ;
    String y="";
       String password ;
    
    public Chiheb_Authentification() {
        initComponents();
          
        this.setLocationRelativeTo(null);
       this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlogin = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Login(email) :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 70, 90, 30);

        jLabel2.setText("Password :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 130, 90, 30);

        jlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloginActionPerformed(evt);
            }
        });
        getContentPane().add(jlogin);
        jlogin.setBounds(190, 70, 101, 30);
        getContentPane().add(jPassword);
        jPassword.setBounds(190, 130, 101, 30);

        jButton1.setText("Inscription");
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 130, 90, 23);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\chiheb\\Desktop\\facebook_square-128.png")); // NOI18N
        jButton2.setText("jButton2");
        getContentPane().add(jButton2);
        jButton2.setBounds(160, 220, 60, 70);

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\chiheb\\Desktop\\twitter_square-128.png")); // NOI18N
        jButton3.setText("jButton3");
        getContentPane().add(jButton3);
        jButton3.setBounds(250, 220, 60, 70);

        jButton4.setText("Connexion");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(330, 70, 90, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jloginActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
Chiheb_Choix_authentification auth = new  Chiheb_Choix_authentification();
        variable2 = auth.get_variable();
         String email=jlogin.getText().toString();
          //String password=jPassword.getPassword().toString();
           char[] s2 = jPassword.getPassword();
    password = new String(s2);
        if (variable2 ==0){
            
        }
        else if (variable2 ==1){
            String  insertStr = "select Id_Personne from personne where email='"+email+"'"; 
             String  insertStr2 = "select mot_de_passe from client where Id_Personne='"+x+"'"; 
            
                    if(email.length()!=0 && password.length()!=0)
                   {
                       try {
            PreparedStatement ps = MyConnection.getInstance().prepareStatement(insertStr);
            
           // PreparedStatement ps3 = MyConnection.getInstance().prepareStatement(insertStr3);
               ResultSet resultat = ps.executeQuery();
          
                while (resultat.next())
            {
              x = resultat.getInt(1);
            }
              if (x>0){  
           //si il ya un Id_personne selected
           PreparedStatement ps2 = MyConnection.getInstance().prepareStatement(insertStr2);
           
            ResultSet resultat2 = ps2.executeQuery();
             while (resultat2.next())
            {
              y = resultat2.getString(1);
                System.out.println(resultat2.getString(1));
                System.out.println(password);
            }
             //passe correct
             if(y.equals(password)==true)
             {
                 System.out.println("connection avec succes");
             }
               if(y.equals(password)==false)
             {
                 System.out.println("connection non aboutie");
             }
              }
           
        } catch (SQLException ex) {
           //Logger.getLogger(PersonneDao.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("erreur lors de connection "+ex.getMessage());
        }
                       
                   }
            
            
        }
        else if (variable2 ==2){
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chiheb_Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chiheb_Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chiheb_Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chiheb_Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chiheb_Authentification().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jlogin;
    // End of variables declaration//GEN-END:variables
}
                             

                                             
