/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pidev.presentation;

import java.util.*;
import javax.mail.Message.RecipientType;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.internet.*;
import pidev.entities.Transport;

/**
 *
 * @author unknown
 */
public class Envoi_Mail extends javax.swing.JPanel {

     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fiche_reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fiche_reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fiche_reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fiche_reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
           String[] to ={"hakim.kh@hotmail.com"};
            if(sendMail("hakim.khanchouch@esprit.tn","08974683H","message to sdfsdf",to)){
            System.out.println("messag sent");
            }
            else 
            System.out.println("non envoyer");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Envoi_Mail().setVisible(true);
            }
        });
    }
   
public static boolean sendMail(String from,String password,String message,String to[]){
String host="smtp.gmail.com";
Properties props=System.getProperties();
props.put("mail.smtp.starttls.enable","true");
props.put("mail.smpt.host",host);
props.put("mail.smtp.user",from);
props.put("mail.smtp.password",password);
props.put("mail.smtp.port",587);
props.put("mail.smtp.auth","true");
Session session=Session.getDefaultInstance(props,null);
MimeMessage mime=new MimeMessage(session);
try{
mime.setFrom(new InternetAddress(from));
InternetAddress[] toAddress=new InternetAddress[to.length];
for(int i=0;i<to.length;i++){
toAddress[i]=new InternetAddress(to[i]);
}
for(int i=0;i<toAddress.length;i++){
mime.addRecipient(RecipientType.TO,toAddress[i]);
}
mime.setSubject("mail using javamil");
mime.setText(message);
        javax.mail.Transport transport=session.getTransport("smtp");
transport.connect(host,from,password);
transport.sendMessage(mime,mime.getAllRecipients());
transport.close();
return true;
}
catch(MessagingException me){
	me.printStackTrace();
}
return false;
}
    
    
    
    public Envoi_Mail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("Envoyer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Annuler");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jButton1)
                .addGap(116, 116, 116)
                .addComponent(jButton2)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(219, 219, 219))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  
        // TODO add your handling code here:


            String[] to ={"hakim.kh@hotmail.com"};
            if(sendMail("hakim.khanchouch@esprit.tn","08974683H","message to sdfsdf",to)){
            System.out.println("messag sent");
            }
            else 
            System.out.println("non envoyer");




    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
