package pidev.presentation;

import java.awt.Color;
import java.awt.Label;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTable;
import pidev.dao.PersonneDAO;
import static pidev.presentation.GraphReaderExample.firstname;
import static pidev.presentation.GraphReaderExample.lastname;

/**
 *
 * @author chiheb
 */
public class Chiheb_Espace_Admin extends javax.swing.JFrame {
    

    
    public Chiheb_Espace_Admin() {
        initComponents();
            var.setVisible(false);
            agences.setVisible(false);
            supprimer.setVisible(false);
            clients.setVisible(false);
            supprimer.setVisible(false);
             num1.setVisible(false);
              num2.setVisible(false);
               num3.setVisible(false);
                num4.setVisible(false);
                supp_signal.setVisible(false);
                details.setVisible(false);

           
           this.setLocationRelativeTo(null);
       this.pack();
        this.getContentPane().setBackground(new Color(52, 152, 219));
     if (Authentification.connecté==1){
            jnconnecté2.setText(firstname+" "+lastname);
//        //System.out.println(""+Authentification.id_connecté_normal);
     }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jnconnecté2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableau = new javax.swing.JTable();
        var = new javax.swing.JButton();
        agences = new javax.swing.JButton();
        clients = new javax.swing.JButton();
        l = new javax.swing.JLabel();
        details = new javax.swing.JButton();
        supp_signal = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        TfRech = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Espace Admin");
        setBackground(new java.awt.Color(244, 219, 171));
        setPreferredSize(new java.awt.Dimension(1094, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Bienvenue :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(769, 4, 71, 15);

        jnconnecté2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jnconnecté2.setText("jLabel2");
        getContentPane().add(jnconnecté2);
        jnconnecté2.setBounds(858, 4, 44, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Espace Admin");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(35, 134, 125, 22);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Deconnexion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(920, 0, 111, 23);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Générer statiqtiques");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 390, 200, 61);

        supprimer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });
        getContentPane().add(supprimer);
        supprimer.setBounds(970, 330, 95, 34);

        num1.setText("1");
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });
        getContentPane().add(num1);
        num1.setBounds(427, 496, 39, 23);

        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });
        getContentPane().add(num2);
        num2.setBounds(472, 496, 39, 23);

        num4.setText("4");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });
        getContentPane().add(num4);
        num4.setBounds(562, 496, 39, 23);

        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });
        getContentPane().add(num3);
        num3.setBounds(517, 496, 39, 23);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("Gestion des Comptes");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(10, 216, 200, 69);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setText("Gestion des Annonces");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(10, 303, 200, 69);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton10.setText("Gestion des Signalisations");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(10, 470, 200, 69);

        jScrollPane1.setViewportView(tableau);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 140, 710, 346);

        var.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        var.setText("Affcher la liste des Agents");
        var.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varActionPerformed(evt);
            }
        });
        getContentPane().add(var);
        var.setBounds(230, 100, 231, 23);

        agences.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        agences.setText("Liste des Agences");
        agences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agencesActionPerformed(evt);
            }
        });
        getContentPane().add(agences);
        agences.setBounds(470, 100, 204, 23);

        clients.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clients.setText("Afficher la lsites des Clients");
        clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientsActionPerformed(evt);
            }
        });
        getContentPane().add(clients);
        clients.setBounds(690, 100, 231, 23);
        getContentPane().add(l);
        l.setBounds(783, 574, 0, 0);

        details.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        details.setText("Afficher Details");
        details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsActionPerformed(evt);
            }
        });
        getContentPane().add(details);
        details.setBounds(953, 257, 126, 57);

        supp_signal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        supp_signal.setText("Supprimer");
        supp_signal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supp_signalActionPerformed(evt);
            }
        });
        getContentPane().add(supp_signal);
        supp_signal.setBounds(970, 380, 95, 35);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Recherche");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(680, 50, 121, 31);

        TfRech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfRechActionPerformed(evt);
            }
        });
        getContentPane().add(TfRech);
        TfRech.setBounds(520, 50, 144, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        jLabel2.setText("recherche par mots- clés");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 30, 225, 64);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Admin.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(35, 0, 128, 128);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         PersonneDAO psd = new PersonneDAO();
        psd.deconnexion(Authentification.id_connecté_normal);
        Accueil chacc = new Accueil();
        chacc.setVisible(true);
        this.dispose();
//        Accueil acc = new Accueil();
//        acc.setVisible(true);
//        PersonneDAO psd = new PersonneDAO();
//        psd.deconnexion(Authentification.id_connecté_normal);
//        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        supp_signal.setVisible(false);
        new Statistiques().setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
    tableau.setModel(new AfficherAnnonce(0,10));
            num1.setVisible(false);
            num2.setVisible(true);
            num3.setVisible(true);
            num4.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_num1ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
               tableau.setModel(new AfficherAnnonce(10,20));
               num1.setVisible(true);
            num2.setVisible(false);
            num3.setVisible(true);
            num4.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_num2ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
                tableau.setModel(new AfficherAnnonce(20,30));
                num1.setVisible(true);
            num2.setVisible(true);
            num3.setVisible(false);
            num4.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_num3ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        // TODO add your handling code here:
                       tableau.setModel(new AfficherAnnonce(30,40));
                       num1.setVisible(true);
            num2.setVisible(true);
            num3.setVisible(true);
            num4.setVisible(false);
    }//GEN-LAST:event_num4ActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        int ligneSelectionne = tableau.getSelectedRow();        
            if(ligneSelectionne!=-1){
                   String s = tableau.getValueAt(ligneSelectionne, 0).toString();    
                    PersonneDAO p=new PersonneDAO();
                    l.setText("");
                    if (p.delete(Integer.parseInt(s)))
                    {
                        OP.showMessageDialog(this, "Suppression effectuer avec succés", "Done !", JOptionPane.INFORMATION_MESSAGE);
                        tableau.setModel(new AfficherAgent());
                    }
                    else{

                        OP.showMessageDialog(this, "Erreur , reessayer", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
                else{ 
                   OP.showMessageDialog(this, "Rien n'est selectionner", "Attention", JOptionPane.INFORMATION_MESSAGE);

                }
            
        // TODO add your handling code here:
    }//GEN-LAST:event_supprimerActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
            
            var.setText("Afficher les Responsables Agents");
            agences.setText("Listes des Agences");
            agences.setVisible(true);
            supprimer.setVisible(true);
            clients.setVisible(true);
            supp_signal.setVisible(false);
            supp_signal.setVisible(false);
            details.setVisible(false);
            var.setVisible(true);
            tableau.setModel(new AfficherAgent());
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
            supprimer.setVisible(false);
            agences.setVisible(false);
            clients.setVisible(false);
            var.setVisible(false);
            num1.setVisible(false);
            num2.setVisible(true);
            num3.setVisible(true);
            num4.setVisible(true);
            details.setVisible(true);
            tableau.setModel(new AfficherAnnonce(0,10));

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
            num1.setVisible(false);
            num2.setVisible(false);
            num3.setVisible(false);
            num4.setVisible(false);
            supprimer.setVisible(false);
            supp_signal.setVisible(true);
            details.setVisible(false);
            tableau.setModel(new signalisation());
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void varActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varActionPerformed

                
                tableau.setModel(new AfficherAgent());
                supprimer.setVisible(true);
            
        // TODO add your handling code here:
    }//GEN-LAST:event_varActionPerformed

    private void agencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agencesActionPerformed
        tableau.setModel(new afficherAgence());
        supprimer.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_agencesActionPerformed

    private void clientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientsActionPerformed
        tableau.setModel(new AfficherClient());
        supprimer.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_clientsActionPerformed

    private void detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsActionPerformed

        int ligneSelectionne = tableau.getSelectedRow();
        if(ligneSelectionne!=-1){
            int id = Integer.parseInt(tableau.getValueAt(ligneSelectionne, 0).toString());
            new Detail_annonce_admin((id)).setVisible(true);
         }
                else{ 
                   OP.showMessageDialog(this, "Rien n'est selectionner", "Attention", JOptionPane.INFORMATION_MESSAGE);
                }
        // TODO add your handling code here:
    }//GEN-LAST:event_detailsActionPerformed

    private void supp_signalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supp_signalActionPerformed
             int ligneSelectionne = tableau.getSelectedRow();        
            if(ligneSelectionne!=-1){
                   String s = tableau.getValueAt(ligneSelectionne, 0).toString();    
                    PersonneDAO p=new PersonneDAO();
                    l.setText("");
                    if (p.delete_Annonce(Integer.parseInt(s)))
                    {
                        OP.showMessageDialog(this, "Suppression effectuer avec succés", "Done !", JOptionPane.INFORMATION_MESSAGE);
                        tableau.setModel(new AfficherAgent());
                    }
                    else{

                        OP.showMessageDialog(this, "Erreur , reessayer", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
                else{ 
                   OP.showMessageDialog(this, "Rien n'est selectionner", "Attention", JOptionPane.INFORMATION_MESSAGE);

                }
        
// TODO add your handling code here:
    }//GEN-LAST:event_supp_signalActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(!TfRech.getText().equals("")){
            tableau.setModel(new AfficherAnnonce(TfRech.getText()));
        }
        else{
            showMessageDialog(this, "Vous devez ecrire quelque chose", "Attention", JOptionPane.INFORMATION_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TfRechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfRechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfRechActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chiheb_Espace_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chiheb_Espace_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chiheb_Espace_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chiheb_Espace_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Chiheb_Espace_Admin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TfRech;
    private javax.swing.JButton agences;
    private javax.swing.JButton clients;
    private javax.swing.JButton details;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jnconnecté2;
    private javax.swing.JLabel l;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton supp_signal;
    private javax.swing.JButton supprimer;
    private javax.swing.JTable tableau;
    private javax.swing.JButton var;
    // End of variables declaration//GEN-END:variables
    JOptionPane OP = new JOptionPane();
}
