
package pidev.presentation;

//import com.sun.xml.internal.ws.message.stream.StreamAttachment;
//import java.util.List;
import java.awt.Color;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import static java.lang.Double.isNaN;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import pidev.dao.AnnonceDAO;
import pidev.dao.EvalDAO;
import pidev.entities.Annonce;

/**
 *
 * @author pikon
 */
public class Detail_annonce_admin extends javax.swing.JFrame {
 static int id_annonce;
 EvalDAO e=new EvalDAO();
    String h = "", description = "", dest = "", nom = "", type_annonce = "", dateDep = "", dateRetour = "", depart = "", heb = "" ,t="" ;

    /**
     * Creates new form Detail_annonce
     */
    public Detail_annonce_admin(int id_Annonce) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.pack();
       
        this.getContentPane().setBackground(new Color(52, 152, 219));
        nb_jaime.setText("");
        AnnonceDAO aDAO = new AnnonceDAO();
        Annonce annonce = aDAO.selectAnnonce(id_Annonce);
        nom = annonce.getNom();
        LabNom.setText(nom);

        dest = annonce.getDestination();
        labdes.setText(dest);

        if(annonce.getType_Annonce()!=null){
            type_annonce = annonce.getType_Annonce();
            if (type_annonce.equals("Affaire")) {
                LabThem.setText(type_annonce);
            } else if (type_annonce.equals("Bien etre")) {
                LabThem.setText(type_annonce);
            } else if (type_annonce.equals("Camping")) {
                LabThem.setText(type_annonce);
            } else if (type_annonce.equals("Excursion")) {
                LabThem.setText(type_annonce);
            } else if (type_annonce.equals("Randonnée")) {
                LabThem.setText(type_annonce);
            } else if (type_annonce.equals("Voyage de découverte")) {
                LabThem.setText(type_annonce);
            } else if (type_annonce.equals("Voyage de noce")) {
                LabThem.setText(type_annonce);
            }
        }
        if(!annonce.getDate_Deb().equals(null)){
        dateDep = annonce.getDate_Deb().toString();
        LabDatDEb.setText(dateDep);
        }
        if(!annonce.getDate_Fin().equals(null)){
        dateRetour = annonce.getDate_Fin().toString();
        LabRet.setText(dateRetour);
        }
        if(!annonce.getDepart().equals(null)){
        depart = annonce.getDepart();
        labdep.setText(depart);
        }
        if(!annonce.getDepart().equals(null)){
        description = annonce.getDescription();
        labdesc.setText(description);
        }
        if(!annonce.getType_hebergement().equals(null)){
        h = annonce.getType_hebergement();

        if (h.equals("Auberge")) {
            LabThem.setText(h);
        } else if (h.equals("Bungalow")) {
            LabThem.setText(h);
        } else if (h.equals("Hotel 1 etoile")) {
            LabThem.setText(h);
        } else if (h.equals("Hotel 2 etoiles")) {
            LabThem.setText(h);
        } else if (h.equals("Hotel 3 etoiles")) {
            LabThem.setText(h);
        } else if (h.equals("Hotel 4 etoiles")) {
            LabThem.setText(h);
        } else if (h.equals("Hotel 5 etoiles")) {
            LabThem.setText(h);
        } else if (h.equals("Residence")) {
            LabThem.setText(h);
        } else if (h.equals("Villa")) {
            LabThem.setText(h);
        }
        }
        if(annonce.getHebergement()!=null){
        heb = annonce.getHebergement();
        labHeberg.setText(heb);
        }
        if(annonce.getDescription()!=null){
               heb = annonce.getDescription();
               labdesc.setText(heb);
               }

        //transport
        //System.out.println(annonce.getTransport());
        if(annonce.getTransport() != null){
            t = annonce.getTransport();
            if (t.equals("AVION")) {
                LabTrans.setText(t);
            } else if (t.equals("BUS")) {
                LabTrans.setText(t);
            } else if (t.equals("MACRO-BUS")) {
                LabTrans.setText(t);
            } else if (t.equals("MINI-BUS")) {
                LabTrans.setText(t);
            } else if (t.equals("VOITURE")) {
                LabTrans.setText(t);
            }
        }
         if(!isNaN(annonce.getPrix())){
                double prix=annonce.getPrix();
                LabPrix.setText(String.valueOf(prix));
            }
       
       



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LabNom = new javax.swing.JLabel();
        LabThem = new javax.swing.JLabel();
        LabDatDEb = new javax.swing.JLabel();
        LabRet = new javax.swing.JLabel();
        labdep = new javax.swing.JLabel();
        labdes = new javax.swing.JLabel();
        labdesc = new javax.swing.JLabel();
        labTypHeb = new javax.swing.JLabel();
        labHeberg = new javax.swing.JLabel();
        LabTrans = new javax.swing.JLabel();
        LabPrix = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        nb_jaime = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(52, 152, 219));
        setForeground(new java.awt.Color(52, 152, 219));
        setPreferredSize(new java.awt.Dimension(900, 676));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(44, 62, 80));
        jLabel2.setText("Date Depart ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 30, 110, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(44, 62, 80));
        jLabel5.setText("Date Retour ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(450, 20, 100, 26);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(44, 62, 80));
        jLabel6.setText("Depart ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 100, 60, 28);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(44, 62, 80));
        jLabel7.setText("Type Hebergement ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(260, 160, 150, 27);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(44, 62, 80));
        jLabel8.setText("Destination ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(270, 100, 100, 32);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(44, 62, 80));
        jLabel9.setText("Description");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 160, 100, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(44, 62, 80));
        jLabel10.setText("Transport ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 240, 100, 17);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Annuler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 350, 90, 23);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(44, 62, 80));
        jLabel12.setText("prix");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(650, 20, 100, 27);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(44, 62, 80));
        jLabel4.setText("Nom ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(38, 26, 60, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(305, 58, 0, 0);

        LabNom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabNom.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(LabNom);
        LabNom.setBounds(90, 20, 135, 24);

        LabThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabThem.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(LabThem);
        LabThem.setBounds(260, 190, 135, 32);

        LabDatDEb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabDatDEb.setForeground(new java.awt.Color(255, 255, 255));
        LabDatDEb.setText("date Depart");
        getContentPane().add(LabDatDEb);
        LabDatDEb.setBounds(280, 60, 90, 26);

        LabRet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabRet.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(LabRet);
        LabRet.setBounds(421, 58, 87, 28);

        labdep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labdep.setForeground(new java.awt.Color(255, 255, 255));
        labdep.setText("dep ");
        getContentPane().add(labdep);
        labdep.setBounds(100, 100, 87, 37);

        labdes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labdes.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(labdes);
        labdes.setBounds(360, 100, 87, 38);

        labdesc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labdesc.setForeground(new java.awt.Color(255, 255, 255));
        labdesc.setText("jLabel13");
        getContentPane().add(labdesc);
        labdesc.setBounds(40, 180, 173, 41);

        labTypHeb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labTypHeb.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(labTypHeb);
        labTypHeb.setBounds(500, 200, 60, 27);

        labHeberg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labHeberg.setForeground(new java.awt.Color(255, 255, 255));
        labHeberg.setText("Hebergement ");
        getContentPane().add(labHeberg);
        labHeberg.setBounds(440, 200, 150, 17);

        LabTrans.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabTrans.setForeground(new java.awt.Color(255, 255, 255));
        LabTrans.setText("jLabel13");
        getContentPane().add(LabTrans);
        LabTrans.setBounds(40, 270, 52, 23);

        LabPrix.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabPrix.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(LabPrix);
        LabPrix.setBounds(640, 50, 60, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("supprimer annonce");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 350, 149, 23);

        tab.setModel(new evaluer(id_annonce));
        jScrollPane2.setViewportView(tab);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(210, 390, 473, 209);

        nb_jaime.setText("0");
        getContentPane().add(nb_jaime);
        nb_jaime.setBounds(480, 350, 10, 20);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Supprimer Commentaire");
        getContentPane().add(jButton3);
        jButton3.setBounds(500, 600, 181, 23);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("voir Destination");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(550, 350, 131, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Hebergement");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(440, 170, 110, 17);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JFrame test = new JFrame("Google Maps");

        try {
            String imageUrl = "https://maps.googleapis.com/maps/api/staticmap?zoom=5&size=512x512&maptype=roadmap\\&markers=size:mid|color:red|"+dest+",TN&sensor=false";
            String destinationFile = "image.jpg";
            String str = destinationFile;
            URL url = new URL(imageUrl);
            InputStream is = url.openStream();
            OutputStream os = new FileOutputStream(destinationFile);

            byte[] b = new byte[2048];
            int length;

            while ((length = is.read(b)) != -1) {
                os.write(b, 0, length);
            }

            is.close();
            os.close();
        } catch (IOException e) {

        }

        test.add(new JLabel(new ImageIcon((new ImageIcon("image.jpg")).getImage().getScaledInstance(630, 600,
            java.awt.Image.SCALE_SMOOTH))));

test.setVisible(true);
test.setLocationRelativeTo(null);
test.pack();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detail_annonce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detail_annonce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detail_annonce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detail_annonce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               new Detail_annonce(id_annonce).setVisible(true);
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabDatDEb;
    private javax.swing.JLabel LabNom;
    private javax.swing.JLabel LabPrix;
    private javax.swing.JLabel LabRet;
    private javax.swing.JLabel LabThem;
    private javax.swing.JLabel LabTrans;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labHeberg;
    private javax.swing.JLabel labTypHeb;
    private javax.swing.JLabel labdep;
    private javax.swing.JLabel labdes;
    private javax.swing.JLabel labdesc;
    private javax.swing.JLabel nb_jaime;
    private javax.swing.JTable tab;
    // End of variables declaration//GEN-END:variables
}
